poem/urls.py
from django.urls import path
from .views import learn_poem, poem_detail

app_name = 'poem'
urlpatterns = [
    path('', learn_poem, name='learn_poem'),
    path('poem_detail/<int:poem_post_id>/', poem_detail, name='poem_detail'),  # <int:poem_post_id> 추가
]

todaypoem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from word.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('word/', include('word.urls')),
    path('poem/', include('poem.urls')),
    path('', home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

word/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from .views import wordPost, learn_word, word_detail,voca



app_name='word'
urlpatterns = [
    path('', learn_word, name='learn_word'),
    path('detail/<str:word>/', word_detail, name='word_detail'),
    path('voca/', voca, name='voca'),
]

word/models.py
from django.contrib.auth import get_user_model
from django.db import models
from poem.models import PoemPost, PostComment


# Create your models here.

class Word(models.Model):
    word = models.CharField(max_length = 10)
    description = models.CharField(max_length = 500)
    example = models.CharField(max_length = 500)
    def __str__(self):
        return self.word
    
class WordUser(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    word = models.ForeignKey(Word, on_delete=models.CASCADE)
    writeTime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.word
    
class Notice(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete = models.CASCADE)
    post = models.ForeignKey(PoemPost, on_delete = models.CASCADE)
    postComment = models.ForeignKey(PostComment, on_delete = models.CASCADE)
    write_time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Notice by {self.user.username} on {self.post}'

word/views.py
import random
import requests
from django.shortcuts import render, get_object_or_404, redirect
from .models import Word, WordUser
import json
from django.conf import settings
from poem.views import generate_and_save_poem
from django.contrib.auth.decorators import login_required
from poem.models import PoemPost, PostComment, Poem
from accounts.models import MyPage
from django.contrib import messages
import os

file_path = os.path.join(settings.BASE_DIR, 'words.txt')  # 단어가 저장된 파일 경로

def get_word_list_from_file(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as file:
            words = file.read().splitlines()
            return words
    except FileNotFoundError:
        print(f"File not found: {file_path}")
        return []

def save_word_list_to_file(word_list, file_path):
    with open(file_path, 'w', encoding='utf-8') as file:
        for word in word_list:
            file.write(word + '\n')

def get_random_word(file_path):
    word_list = get_word_list_from_file(file_path)
    if not word_list:
        return None
    word = random.choice(word_list)
    word_list.remove(word)
    save_word_list_to_file(word_list, file_path)
    return word

def get_word_data_from_api(word):
    SORI_TOKEN = settings.SORI_TOKEN
    api_url = f"https://opendict.korean.go.kr/api/search?key={SORI_TOKEN}&q={word}&req_type=json&part=word"
    response = requests.get(api_url)
    api_url_ex = f"https://opendict.korean.go.kr/api/search?key={SORI_TOKEN}&q={word}&req_type=json&part=exam"
    response_ex = requests.get(api_url_ex)
    
    if response.status_code == 200:
        try:
            data = response.json()
            data_ex = response_ex.json()
            print(data)
            # API 응답 형식에 따라 데이터 파싱하는 것 (아래는 콘솔 디버깅용)
            print(data['channel']['item'][0]['word'])
            print(data['channel']['item'][0]['sense'][0]['definition'])
            return {
                'word': data['channel']['item'][0]['word'],
                'description': data['channel']['item'][0]['sense'][0]['definition'],
                'example': data_ex['channel']['item'][0]['example']
            }
        except (KeyError, IndexError, ValueError, json.JSONDecodeError) as e:
            print(f"Error parsing API response: {e}")
            print(f"Response Content: {response.text}")
            return None
    else:
        print(f"Response Content: {response.text}")
        return None

def save_word_to_db(word_data):
    word = Word(
        word=word_data['word'],
        description=word_data['description'],
        example=word_data['example'],
    )
    word.save()

def fetch_and_save_random_word(file_path):
    word = get_random_word(file_path)
    if not word:
        print("No more words available.")
        return None
    word_data = get_word_data_from_api(word)
    print("DATA: ", word_data)
    if word_data:
        save_word_to_db(word_data)
        return word_data

def wordPost():
    fetch_and_save_random_word(file_path)
    generate_and_save_poem() 

@login_required
def home(request):
    try:
        user_profile = MyPage.objects.get(user=request.user)
        profile_image = user_profile.profile_image.url if user_profile.profile_image else None
    except MyPage.DoesNotExist:
        profile_image = None

    word_obj = Word.objects.latest('id')
    latest_word = word_obj.word
    count_lday = WordUser.objects.filter(user=request.user).count()
    all = WordUser.objects.filter(user=request.user).order_by('-id')[:3]
    return render(request, 'home.html', {'word':latest_word, 'lday':count_lday, 'allWords':all, 'profile_image':profile_image})
@login_required
def learn_word(request):
    try:
        user_profile = MyPage.objects.get(user=request.user)
        profile_image = user_profile.profile_image.url if user_profile.profile_image else None
    except MyPage.DoesNotExist:
        
        profile_image = None

    word_obj = Word.objects.latest('id')
    word = word_obj.word
    if WordUser.objects.filter(user=request.user).filter(word=word_obj).exists():
        messages.warning(request, '이미 학습한 단어 입니다. 새로운 단어 학습 시간까지 기다려주세요!')
        # home 페이지로 리디렉션
        return redirect('/')
    desc=word_obj.description
    exam=word_obj.example
    count_lday = WordUser.objects.filter(user=request.user).count()
    return render(request, 'learning.html', {'word':word, 'desc':desc, 'exam':exam, 'lday':count_lday,'profile_image':profile_image})

def voca(request):
    try:
        user_profile = MyPage.objects.get(user=request.user)
        profile_image = user_profile.profile_image.url if user_profile.profile_image else None
    except MyPage.DoesNotExist:
       
        profile_image = None
    try:
        word = WordUser.objects.filter(user=request.user).latest('id')
        print(word.word)
        return redirect('word:word_detail', word=word.word)
    except WordUser.DoesNotExist:
        message = "아직 학습한 단어가 없습니다."
        return render(request, 'myVocabulary.html', {'message': message, 'profile_image':profile_image})


@login_required
def word_detail(request, word):
    try:
        user_profile = MyPage.objects.get(user=request.user)
        profile_image = user_profile.profile_image.url if user_profile.profile_image else None
    except MyPage.DoesNotExist:
        profile_image = None
    word = get_object_or_404(Word, word=word)
    wordUser = WordUser.objects.filter(user=request.user).filter(word=word)
    desc=word.description
    exam=word.example
    date=wordUser[0].writeTime
    
    # 해당 단어를 학습한 사용자들의 목록 가져오기
    #allWords = WordUser.objects.filter(user=request.user).order_by('-id')
    
    # 해당 단어와 관련된 시(post) 가져오기
    poem = get_object_or_404(Poem, word=word).poem
    post_auth = get_object_or_404(PoemPost, poem__word=word, user=request.user)
    user_post_comments = PostComment.objects.filter(post= post_auth).order_by('id')
    
    context = {
        'word': wordUser,
        'word_jin':word.word,
        'desc': desc,
        'exam': exam,
        'poem': poem,
        'allWords': WordUser.objects.filter(user=request.user).order_by('-id'),  # 사용자 단어 목록 다시 가져오기
        'date':date,
        'post_auth': post_auth,
        'user_post_comments':  user_post_comments,
        'profile_image': profile_image,
    }
    
    return render(request, 'myVocabulary.html', context)

word/templates/home.html
{% extends "base.html" %}
{% load static %}


  
{% block static %}
  <link rel="stylesheet" href="{% static 'css/home.css'  %}" />
  <!--이 곳에 static에 해당하는 코드 (css파일 연결 등) 작성-->
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link
    href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap"
    rel="stylesheet"
  />
{% endblock %}
{% block content %}

{% if messages %}
<div class="messagebox">
  <ul class="messages">
      {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }} message-content"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
</div>
{% endif %}

    <div class="hd">
      <div>
        <h1 class="hi">
            {{ request.user.username }}님, 안녕하세요 ! <br />오늘의 단어를 학습해볼까요?
        </h1>
        <h2 class="continue">🔥 {{ lday }}일째 학습중</h2>
      </div>
      <div class="sec">
        <div class="learning">
          <div class="intro1">오늘의 학습</div>
          <div class="word-box">
            <div class="word-title">{{ word }}</div>
            <a href="{% url 'word:learn_word' %}" class="learning-btn">
              <div class="go-learning">
                ‘{{ word }}’가 포함된 시 학습하러 가기
              </div>
            </a>
          </div>
        </div>
        <div class="word">
          <div class="intro2">내 단어장</div>
          <div>
            {% for word in allWords %}
                <a href="{% url 'word:word_detail' word=word.word %}" class="word-link1"
                ><img
                    class="word1"
                    src="{% static 'img/단어장 배경.svg' %}"
                    alt="new-word" />
                <div class="name">{{ word.word }}</div>
                <div class="date">학습일: {{ word.writeTime|date:"m/d" }}</div>
                <img class="go" src="{% static 'img/arrow-right.svg' %}" alt="arrow"
                /></a>
            {% endfor %}
          </div>
          <div>
         
          <a href="{% url 'word:voca' %}"><div class="go-word">전체보기</div></a>
          
        </div>
      </div>
    </div>
    <script src="{% static 'js/home.js'%}"></script>
{% endblock %}

word/templates/learning.html
{% extends "base.html" %} {% load static %} {% block static %}
<link rel="stylesheet" href="{% static 'css/learning.css'  %}" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap"
  rel="stylesheet"
/>
{% endblock %} {% block content %}

<div class="hd">
  <div>
    <h1 class="hi">
      {{ request.user.username }}님, 안녕하세요 !<br />오늘의 단어를
      학습해볼까요?
    </h1>
    <h2 class="continue">🔥 {{ lday }}일째 학습중</h2>
  </div>
  <div class="step">
    <div class="step1">
      <img class="first" src="{% static 'img/step1-click.svg' %}" alt="step1" />
      <p class="word">오늘의 단어</p>
    </div>
    <img class="line" src="{% static 'img/점선.svg' %}" alt="line" />
    <div class="step2">
      <img class="second" src="{% static 'img/step2-non.svg' %}" alt="step2" />
      <p class="poem">오늘의 시</p>
    </div>
  </div>
  <div class="content">
    <div class="introduce">💁‍♀️</div>
    <div class="meaning">
      "{{ word }}"는 '{{ desc }}'는 의미를 가진 한국어 표현입니다.
    </div>
    <!--
        <div class="similar">
          <div class="equal">🟰</div>
          <div class="synonym">
            유의어로는 ‘철상철하', ‘철저히' 가 있습니다.
          </div>
        </div>
        -->
    <div class="instance">
      <div class="pencil">✏️</div>
      <div class="example">‘{{ exam }}’ 와 같이 사용됩니다.</div>
    </div>
    <a href="{% url 'poem:learn_poem' %}" class="go-btn">
      <div class="go">‘{{ word }}’가 포함된 시 학습하러 가기</div>
    </a>
  </div>
</div>
{% endblock %}

word/templates/myVocabulary.html
{% extends "base.html" %}
{% load static %}
  
{% block static %}

    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'css/myVocabulary.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100..900&display=swap" rel="stylesheet">
{% endblock %}
{% block content %}
       <div class="main">
            <div class="text">
                <p>지금까지 열심히 학습한 단어들을 복습해봅시다</p>
                <p> 🔥 단어는 보고 또 볼수록 익숙해진다는 사실! 잊지 마세요 </p>
            </div>
            <div class="dataDiv">
                {% if message %}
                    <p>{{ message }}</p>
                {% else %}
                <div class="wordDivs">
                    {% for word in allWords %}
                    <a href="{% url 'word:word_detail' word=word.word %}" class="box">
                        <div class="wordDiv">
                            <div class="wordText">
                                <p>{{ word.word }}</p>
                                <p>학습일: {{ date|date:"m/d" }}</p>
                            </div>
                            <img src="{% static 'img/arrow-right.svg' %}" alt="arrow">
                        </div>
                        <div class="linebox">
                            <hr class="line">
                        </div>
                    </a>
                    {% endfor %}
                </div>


                <div class="wordData">
                    <div class="dataSection">
                        <p class="dataTitle">{{ date|date:"m/d" }}의 단어</p>
                        <div class="word">
                            <p>💁‍♀️</p>
                            <p>
                                "{{ word_jin }}"은/는 '{{ desc }}'(이)라는 
                                의미를 가진 한국어 표현입니다.<br>
                                ✏️{{ exam }}
                            </p>
                            
                        </div>
                    </div>
                    <hr>
                    <div class="dataSection">
                        <p class="dataTitle">{{ date|date:"m/d" }}의 시</p>
                        <div class="poem">
                            <P>
                                {{ poem }}
                            </P>
                        </div>
                    </div>
                    <hr>
                    <div class="dataDiv">
                        <article class="review-container">  <!-- 오버플로우 설정할 박스 -->
                            <div class="review-wrap">    <!-- 사용자 리뷰, 다른 사람 리뷰를 묶어줌 -->
                                <!-- 로그인한 사용자 감상 -->
                                <article class="user-review">
                                    <div class="user-profile">  <!-- 유저 닉네임 정보 (프로필사진 + 이름 + 유저라벨) -->
                                        <div class="user-profile-left">
                                            {% if post_auth.user.userImage %}
                                                <img src="{{ post_auth.user.userImage.url }}" alt="Image">
                                            {% else %}
                                                <img src="{% static 'img/alarmImg.svg' %}" alt="Default Image">
                                            {% endif %}
                                            <div class="user-name">{{ post_auth.user.username }}</div>
                                            <div class="user-label">나</div>
                                        </div>
                                        <!-- 오른쪽 수정 버튼 -->
                                        <img class="edit-btn" src="{% static 'img/ellipsis-vertical-sharp.svg' %}" alt="example"/>
                                    </div>
                                    <!-- 리뷰 불러오는 박스 -->
                                    <div class="review-box">
                                        <div class="review">{{ post_auth.post }}</div>
                                        <div class="date">{{ post_auth.write_time|date:"m/d" }}</div>
                                         <!-- 댓글입력 btn -->
                                        <div class="reply-btn">답글달기</div>
                                    </div>
                                <!-- 감상에 달린 댓글들 보여주는 파트 -->
                                {% if user_post_comments %}
                                <article class="replys">
                                {% for comment in user_post_comments %}
                                    <div class="user-profile">  <!-- 유저 닉네임 정보 (프로필사진 + 이름 + 유저라벨) -->
                                        <div class="user-profile-left">
                                            <img class="space-img" src="{% static 'img/ㄴ.svg' %}">
                                                <!--<img class="profile-img" src="{% static 'img/Ellipse 14.svg' %}"alt="example"/>-->
                                            {% if comment.user.userImage %}
                                                <img class="profile-img" src="{{ comment.user.userImage.url }}" alt="Image"> <!-- 프로필 이미지 -->
                                            {% else %}
                                                <img class="profile-img" src="{% static 'img/alarmImg.svg' %}" alt="Default Image">
                                            {% endif %}
                                            <div class="user-name">{{ comment.user.username }}</div>
                                            <div class="user-label">나</div>
                                        </div>
                                        <!-- 오른쪽 수정 버튼 -->
                                        <img class="edit-btn" src="{% static 'img/ellipsis-vertical-sharp.svg' %}" alt="example"/>
                                    </div>
                                    <!-- 댓글내용 -->
                                    <div class="review-box">
                                        <div class="review">{{ comment.comment }}</div>
                                        <div class="date">{{ comment.write_time|date:"m/d" }}</div>
                                    </div>
                                    {% endfor %}
                                </article>
                                {% endif %}   
                            </div>
                    </article>
                </div>
                {% endif %}   
            </div>
        </div>
            
       <!--<script src="{% static 'js/myVocabulary.js'%}"></script>-->
       {%endblock%}