accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from accounts.views import signup, login, logout, mypageUpdate
from django.conf import settings
from django.conf.urls.static import static

app_name='accounts'
urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name= 'logout'),
    path('setting/', mypageUpdate, name= 'setting'),
    
    
    
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

poem/urls.py
from django.urls import path
from .views import learn_poem, poem_detail

app_name = 'poem'
urlpatterns = [
    path('', learn_poem, name='learn_poem'),
    path('poem_detail/<int:poem_post_id>/', poem_detail, name='poem_detail'),  # <int:poem_post_id> 추가
]

todaypoem/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from word.views import home
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('word/', include('word.urls')),
    path('poem/', include('poem.urls')),
    path('', home, name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

word/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from .views import wordPost, learn_word, word_detail,voca



app_name='word'
urlpatterns = [
    path('', learn_word, name='learn_word'),
    path('detail/<str:word>/', word_detail, name='word_detail'),
    path('voca/', voca, name='voca'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>오늘의 시</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      type="text/css"
      media="screen"
      href="{% static 'css/profileSetting.css' %}"
    />
    {% block static %} {% endblock %}
    <style>
      html,
      body {
        margin: 0;
        padding: 0;
        width: 100%;
        height: 100%;
      }
    </style>
  </head>
  <body>
    <nav>
      <div class="container">
        <img class="logo" src="{% static 'img/logo.svg' %}" alt="logo" />
        <div class="nav-menu">
          <ul class="nav-btn">
            {% if user.is_authenticated %}
            <li><a class="home menu-text" href="{% url 'home' %}">홈</a></li>
            <li>
              <a class="learn menu-text" href="{% url 'word:learn_word' %}"
                >학습</a
              >
            </li>
            <li>
              <a class="wordlist menu-text" href="{% url 'word:voca' %}"
                >단어장</a
              >
            </li>
            <li>
              <button class="alarmBtn button">
                <img src="{% static 'img/alarm.svg' %}" alt="alarm" />
              </button>
            </li>
            <li>
              <button class="profileBtn button">
                <img src="{% static 'img/myPage.svg' %}" alt="mypage" />
              </button>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="alarm-modal">
      <div class="alarm-content">
        <p>알림</p>
        <hr />
        <div class="alarmlist">
          <div class="alarm-img">
            <img src="{% static 'img/alarmImg.svg' %}" alt="alarmImg" />
          </div>
          <div class="alarm-text">
            <p>오늘의 단어 학습이 도착했어요!</p>
            <p>방금</p>
          </div>
        </div>
        <div class="alarmlist">
          <div class="alarm-img">
            <img src="{% static 'img/alarmImg.svg' %}" alt="alarmImg" />
          </div>
          <div class="alarm-text">
            <p>단어짱님이 내 감상에 댓글을 남겼어요.</p>
            <p>1일전</p>
          </div>
        </div>
        <div class="alarmlist">
          <div class="alarm-img">
            <img src="{% static 'img/alarmImg.svg' %}" alt="alarmImg" />
          </div>
          <div class="alarm-text">
            <p>오늘의 시 감상을 작성해 학습을 마무리해보세요!</p>
            <p>1일전</p>
          </div>
        </div>
        <div class="alarmlist">
          <div class="alarm-img">
            <img src="{% static 'img/alarmImg.svg' %}" alt="alarmImg" />
          </div>
          <div class="alarm-text">
            <p>오늘의 시 감상을 작성해 학습을 마무리해보세요!</p>
            <p>1일전</p>
          </div>
        </div>
      </div>
    </div>
    <div class="profile-modal">
      <div class="profile-content">
        <div class="profile-header">
          <div class="profile-image">
            <img src="{% static 'img/alarmImg.svg' %}" alt="Profile Image" />
          </div>
        </div>
        <div class="profile-details">
          <p class="profile-name">{{ request.user.username }}</p>
          <p class="profile-email">{{ request.user.email }}</p>
        </div>
        <hr />
        <div class="profile-actions">
          <button class="action-button">
            <img src="{% static 'img/logout.svg' %}" />
            <a href="{% url 'accounts:logout' %}">로그아웃</a>
          </button>
          <button class="action-button">
            <img src="{% static 'img/setting.svg' %}" />
            <a href="{% url 'accounts:setting' %}">계정설정</a>
          </button>
        </div>
      </div>
    </div>
    {% block content %} {% endblock %}
    <script src="{% static 'js/profileSetting.js' %}"></script>
  </body>
</html>